// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScottNet.Web.Data;

namespace ScottNet.Web.Migrations
{
    [DbContext(typeof(ScottDbContext))]
    [Migration("20190128163808_BarometricTrends")]
    partial class BarometricTrends
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScottNet.Web.Data.Entities.BarometricTrend", b =>
                {
                    b.Property<short>("Id");

                    b.Property<short>("Code");

                    b.Property<string>("Title")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("BarometricTrends");
                });

            modelBuilder.Entity("ScottNet.Web.Data.Entities.WeatherReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Barometer");

                    b.Property<short?>("BarometricTrendId");

                    b.Property<DateTime>("ConsoleTime")
                        .HasColumnType("DateTime2(1)");

                    b.Property<short>("DewPoint");

                    b.Property<bool>("ForecastCloudyIcon");

                    b.Property<byte>("ForecastIcon");

                    b.Property<bool>("ForecastPartlyCloudyIcon");

                    b.Property<bool>("ForecastRainIcon");

                    b.Property<bool>("ForecastSnowIcon");

                    b.Property<bool>("ForecastSunIcon");

                    b.Property<short>("HeatIndex");

                    b.Property<byte>("IndoorHumidity");

                    b.Property<float>("IndoorTemp");

                    b.Property<byte>("OutdoorHumidity");

                    b.Property<float>("OutdoorTemp");

                    b.Property<float>("Rain15M");

                    b.Property<float>("Rain1H");

                    b.Property<float>("Rain24H");

                    b.Property<float>("RainDay");

                    b.Property<float>("RainMonth");

                    b.Property<float>("RainRate");

                    b.Property<float>("RainStorm");

                    b.Property<float>("RainYear");

                    b.Property<short>("WindChill");

                    b.Property<short>("WindDirection");

                    b.Property<short>("WindGustDirection10M");

                    b.Property<float>("WindGustSpeed10M");

                    b.Property<float>("WindSpeed");

                    b.Property<float>("WindSpeed10M");

                    b.Property<float>("WindSpeed2M");

                    b.HasKey("Id");

                    b.HasIndex("BarometricTrendId");

                    b.ToTable("WeatherReadings");
                });

            modelBuilder.Entity("ScottNet.Web.Data.Entities.WeatherReading", b =>
                {
                    b.HasOne("ScottNet.Web.Data.Entities.BarometricTrend", "BarometricTrend")
                        .WithMany()
                        .HasForeignKey("BarometricTrendId");
                });
#pragma warning restore 612, 618
        }
    }
}
