// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScottNet.Web.Data;

namespace ScottNet.Web.Migrations
{
    [DbContext(typeof(ScottDbContext))]
    partial class ScottDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ScottNet.Web.Data.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<long?>("GoogleId");

                    b.Property<string>("InitialIP");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("PictureUrl");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ScottNet.Web.Data.Entities.BarometricTrend", b =>
                {
                    b.Property<short>("Id");

                    b.Property<short>("Code");

                    b.Property<string>("Title")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("BarometricTrends");
                });

            modelBuilder.Entity("ScottNet.Web.Data.Entities.ImageFormatSpec", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("FileNameSuffix")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<int>("FormatOrder");

                    b.Property<int?>("JpegQuality");

                    b.Property<int?>("MaxWidth");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int?>("PngCompression");

                    b.HasKey("Id");

                    b.ToTable("ImageFormatSpecs");
                });

            modelBuilder.Entity("ScottNet.Web.Data.Entities.ImageGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("PathToOriginal")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<DateTime>("UploadDate");

                    b.Property<string>("UploadUserId");

                    b.HasKey("Id");

                    b.HasIndex("UploadUserId");

                    b.ToTable("ImageGroups");
                });

            modelBuilder.Entity("ScottNet.Web.Data.Entities.ImageInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("ImageFormatSpecId");

                    b.Property<int>("ImageGroupId");

                    b.Property<string>("SharedUrl")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<int>("Size");

                    b.Property<string>("Url")
                        .HasColumnType("VARCHAR(300)");

                    b.HasKey("Id");

                    b.HasIndex("ImageFormatSpecId");

                    b.HasIndex("ImageGroupId");

                    b.ToTable("ImageInstances");
                });

            modelBuilder.Entity("ScottNet.Web.Data.Entities.WeatherReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Barometer");

                    b.Property<short?>("BarometricTrendId");

                    b.Property<DateTime>("ConsoleTime")
                        .HasColumnType("DateTime2(1)");

                    b.Property<short>("DewPoint");

                    b.Property<bool>("ForecastCloudyIcon");

                    b.Property<byte>("ForecastIcon");

                    b.Property<bool>("ForecastPartlyCloudyIcon");

                    b.Property<bool>("ForecastRainIcon");

                    b.Property<bool>("ForecastSnowIcon");

                    b.Property<bool>("ForecastSunIcon");

                    b.Property<short>("HeatIndex");

                    b.Property<byte>("IndoorHumidity");

                    b.Property<float>("IndoorTemp");

                    b.Property<byte>("OutdoorHumidity");

                    b.Property<float>("OutdoorTemp");

                    b.Property<float>("Rain15M");

                    b.Property<float>("Rain1H");

                    b.Property<float>("Rain24H");

                    b.Property<float>("RainDay");

                    b.Property<float>("RainMonth");

                    b.Property<float>("RainRate");

                    b.Property<float>("RainStorm");

                    b.Property<float>("RainYear");

                    b.Property<short>("WindChill");

                    b.Property<short>("WindDirection");

                    b.Property<short>("WindGustDirection10M");

                    b.Property<float>("WindGustSpeed10M");

                    b.Property<float>("WindSpeed");

                    b.Property<float>("WindSpeed10M");

                    b.Property<float>("WindSpeed2M");

                    b.HasKey("Id");

                    b.HasIndex("BarometricTrendId");

                    b.ToTable("WeatherReadings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ScottNet.Web.Data.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ScottNet.Web.Data.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScottNet.Web.Data.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ScottNet.Web.Data.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScottNet.Web.Data.Entities.ImageGroup", b =>
                {
                    b.HasOne("ScottNet.Web.Data.Entities.AppUser", "UploadUser")
                        .WithMany("Images")
                        .HasForeignKey("UploadUserId");
                });

            modelBuilder.Entity("ScottNet.Web.Data.Entities.ImageInstance", b =>
                {
                    b.HasOne("ScottNet.Web.Data.Entities.ImageFormatSpec", "ImageFormatSpec")
                        .WithMany()
                        .HasForeignKey("ImageFormatSpecId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScottNet.Web.Data.Entities.ImageGroup", "ImageGroup")
                        .WithMany("ImageInstances")
                        .HasForeignKey("ImageGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScottNet.Web.Data.Entities.WeatherReading", b =>
                {
                    b.HasOne("ScottNet.Web.Data.Entities.BarometricTrend", "BarometricTrend")
                        .WithMany()
                        .HasForeignKey("BarometricTrendId");
                });
#pragma warning restore 612, 618
        }
    }
}
